# Implementing all the operations of the matrix using NumPy

## 1. Importing NumPy

In [9]:
# pip install numpy

In [3]:
import numpy as np

## 2. Creating Matrices
You can create matrices using `np.array()`. Here's how to create two matrices:

In [4]:
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


- ``np.array()`` converts a list of lists into a NumPy array (matrix).
- ``\n`` is used for better formatting in the output.

## 3. Matrix Addition
To add matrices, use the `+` operator directly.

In [5]:
# Matrix addition
C = A + B
print("\nMatrix Addition (A + B):\n", C)


Matrix Addition (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


- `NumPy` allows element-wise addition directly using `+`.

## 4. Matrix Subtraction
To subtract matrices, use the `-` operator directly.

In [6]:
# Matrix subtraction
D = A - B
print("\nMatrix Subtraction (A - B):\n", D)


Matrix Subtraction (A - B):
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


## 5. Matrix Multiplication (Element-wise)
To multiply matrices element-wise, use `*` directly.

In [7]:
# Element-wise multiplication
E = A * B
print("\nElement-wise Multiplication (A * B):\n", E)


Element-wise Multiplication (A * B):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


## 6. Matrix Multiplication (Dot Product)
For matrix multiplication (dot product), use `np.dot()` or the `@` operator.


In [8]:
# Matrix multiplication (dot product)
F = np.dot(A, B)
G = A @ B
print("\nMatrix Multiplication using np.dot() (A · B):\n", F)
print("\nMatrix Multiplication using @ (A · B):\n", G)


Matrix Multiplication using np.dot() (A · B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix Multiplication using @ (A · B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


- np.dot(A, B) computes the dot product (sum of products of corresponding elements).
- Alternatively, you can use F = A @ B.

## 7. Matrix Transpose
To transpose a matrix, use `.T`

In [10]:
# Transposing a matrix
A_T = A.T
print("\nTranspose of Matrix A:\n", A_T)


Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## 8. Determinant of a Matrix
To find the determinant, use `np.linalg.det()`.

In [11]:
# Determinant of a matrix
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:", det_A)


Determinant of Matrix A: 0.0


## 9. Inverse of a Matrix
To compute the inverse, use `np.linalg.inv()`. Make sure the determinant is not zero.

In [12]:
if det_A != 0:
    A_inv = np.linalg.inv(A)
    print("\nInverse of Matrix A:\n", A_inv)
else:
    print("\nMatrix A is singular and cannot be inverted.")


Matrix A is singular and cannot be inverted.


## 10. Summary of All Operations

In [13]:
print("\nSummary:")
print("A + B:\n", C)
print("\nA - B:\n", D)
print("\nA * B (Element-wise):\n", E)
print("\nA · B (Dot Product):\n", F)
print("\nA Transpose:\n", A_T)
print("\nDeterminant of A:", det_A)
if det_A != 0:
    print("\nInverse of A:\n", A_inv)


Summary:
A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

A - B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

A * B (Element-wise):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

A · B (Dot Product):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

A Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant of A: 0.0


### Thank You